name: Deploy
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install and configure poetry
        run: python -m pip install poetry
      - name: Install python packages
        run: python -m poetry install
      - name: Bump files
        run: python -m poetry run python run-ci.py deploy --git-tag "$(git describe --tags)"
      - name: Build
        run: poetry build
      - name: Publish
        run: poetry publish
