name: Deploy
on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install and configure poetry
        run: python -m pip install poetry
      - name: Install python packages
        run: python -m poetry install
      - name: Bump files
        run: python -m poetry run python run-ci.py bump --git-tag "${GITHUB_REF#refs/tags/}"
      - name: Build
        run: python -m poetry build
      - name: Auth
        run: python -m poetry config pypi-token.pypi "${PYPI_API_TOKEN}"
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      - name: Publish
        run: python -m poetry publish
