name: safety
on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  safety:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure poetry
        run: |
          python -m pip install poetry
          python -m poetry config virtualenvs.create false

      - name: Prepare project for development
        run: python -m poetry install

      # NOTE: Ignore issue 70612 in all versions of Jinja2 (not affected)
      - name: Run safety dependency check
        run: python -m poetry run safety check --full-report -i 70612
