name: tests
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install and configure poetry
        run: |
          python -m pip install poetry
          python -m poetry config virtualenvs.create false

      - name: Prepare project for development
        run: python -m poetry install

      - name: Run tests
        run: python -m poetry run pytest --cov tankersdk_identity

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
